### ISSUE TITLE
top nodes with remote edges prompt an error

### ISSUE THREAD

**Issue by lovodkin93** [cfmrp/mtool#87]
Hello,
I am using the package in order to convert from mrp to ucca graphs (in xml), and for some mrp files, with top nodes that have remote edges going out of them, the code crashes and prompts the following error:
`AttributeError: 'NoneType' object has no attribute 'add_multiple'`.

I have found the origin of the problem:
in [queue initializaion](https://github.com/cfmrp/mtool/blob/master/codec/ucca.py#L157) , the `unit` side of the `(node, unit)` tuple in queue for top node is initialized to be None. But, if the top node has a remote edge, then in [is_remote](https://github.com/cfmrp/mtool/blob/master/codec/ucca.py#L171) its unit (which is None) is added to the remotes list, together with the target unit's id and the edges label. Finally, in [for loop in remotes](https://github.com/cfmrp/mtool/blob/master/codec/ucca.py#L183), the [add_remote_multiple](https://github.com/cfmrp/mtool/blob/master/ucca/layer1.py#L464) is called, in which the `add_multiple` attribute of `parent` is called, which in the case of the top node is None.

So, my question is - is it illegal for top nodes to have remote edges? If not, then how can I avert this discrepancy between the initialization of the top node's unit and the call to the `add_multiple` attribute of the parent in (https://github.com/cfmrp/mtool/blob/master/codec/ucca.py#L183), the [add_remote_multiple]?
Thanks!
p.s. I have added one of the mrps with this feature as reference.

[prediction_ucca_eng_101.json.tar.gz](https://github.com/cfmrp/mtool/files/6831810/prediction_ucca_eng_101.json.tar.gz)

**Comment by danielhers** [comment]
Manually annotated graphs will never have remote children of the root since it violates the validation rules. But we can let parsers output such graphs and just penalize them in the normal evaluation score. So it should be converted faithfully in my opinion. 
The UCCA library lets you create children of the root by using None as the parent, but only for primary children. It doesn't work for remote children because it was never expected to happen. But technically it can just as well be done the same way. You can set how add_multiple handles this case and do the same for the remote counterpart by adding a function to the Layer1 class or just implementing it inline.

**Comment by lovodkin93** [comment]
great, that is what I will do.
Thank you!
